package com.adoptimizer.config;

import com.adoptimizer.model.AdType;
import com.adoptimizer.model.Audience;
import com.adoptimizer.model.Campaign;
import com.adoptimizer.model.CampaignStatus;
import com.adoptimizer.model.DailyStat;
import com.adoptimizer.model.Notification;
import com.adoptimizer.model.NotificationType;
import com.adoptimizer.model.OptimizationLog;
import com.adoptimizer.model.OptimizationType;
import com.adoptimizer.model.Payment;
import com.adoptimizer.model.Role;
import com.adoptimizer.model.SupportTicket;
import com.adoptimizer.model.SystemSettings;
import com.adoptimizer.model.TicketPriority;
import com.adoptimizer.model.TicketStatus;
import com.adoptimizer.model.User;
import com.adoptimizer.repository.CampaignRepository;
import com.adoptimizer.repository.DailyStatRepository;
import com.adoptimizer.repository.NotificationRepository;
import com.adoptimizer.repository.OptimizationLogRepository;
import com.adoptimizer.repository.PaymentRepository;
import com.adoptimizer.repository.SettingsRepository;
import com.adoptimizer.repository.TicketRepository;
import com.adoptimizer.repository.UserRepository;
import com.adoptimizer.service.TrafficModel;
import com.adoptimizer.util.TimeUtils;
import com.adoptimizer.validation.KeywordListValidator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Fills an empty database with demo accounts, payments, campaigns (with up to 90 days of statistics generated by
 * the same {@link TrafficModel} the live simulator uses), tickets and notifications. Dates are relative to today,
 * so the demo always looks current. Runs only when the users table is empty.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DataSeeder implements ApplicationRunner {

    private final AppProperties properties;
    private final PasswordEncoder passwordEncoder;
    private final UserRepository userRepository;
    private final CampaignRepository campaignRepository;
    private final DailyStatRepository dailyStatRepository;
    private final PaymentRepository paymentRepository;
    private final NotificationRepository notificationRepository;
    private final TicketRepository ticketRepository;
    private final OptimizationLogRepository optimizationLogRepository;
    private final SettingsRepository settingsRepository;

    /** Fixed seed: every fresh database gets the same demo numbers. */
    private final Random random = new Random(42);

    private LocalDate today;
    private LocalDateTime now;
    private SystemSettings settings;

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        if (!properties.getSeed().isEnabled() || userRepository.count() > 0) {
            return;
        }
        today = LocalDate.now();
        now = TimeUtils.now();
        settings = settingsRepository.get();
        log.info("Empty database detected - inserting demo data");

        long admin = user("Platform Admin", "admin@adpro.com", "admin123", "Operations", Role.ADMIN, true, 120);
        long demo = user("Alex Morgan", "demo@adpro.com", "demo123", "Brightline Studio", Role.ADVERTISER, true, 90);
        long priya = user("Priya Nair", "priya@freshcart.io", "password123", "FreshCart", Role.ADVERTISER, true, 60);
        long daniel = user("Daniel Okafor", "daniel@voltgear.com", "password123", "VoltGear", Role.ADVERTISER, true, 45);
        long sofia = user("Sofia Rossi", "sofia@nestliving.co", "password123", "Nest Living", Role.ADVERTISER, false, 100);

        // ---- payments (funds must cover every reserved budget)
        payment(demo, "2500.00", "Visa", "4242", 88);
        payment(demo, "1500.00", "Mastercard", "5454", 45);
        payment(demo, "2000.00", "Visa", "4242", 12);
        payment(priya, "3000.00", "Visa", "1881", 58);
        payment(daniel, "2500.00", "Amex", "0005", 40);
        payment(daniel, "1500.00", "Amex", "0005", 8);
        payment(sofia, "800.00", "Discover", "1117", 95);

        // ---- demo advertiser campaigns
        Campaign autumn = campaign(demo, "Autumn Collection Launch",
                "Introduce our new autumn clothing line with lookbook imagery and a 15% launch discount for new customers.",
                Audience.MILLENNIALS, AdType.IMAGE, "2000", "30", -40, 50, "fashion, autumn, new collection",
                CampaignStatus.ACTIVE, -1, false, "1.00");
        Campaign smartHome = campaign(demo, "Smart Home Starter Kit",
                "Bundle offer for our smart plugs, hub and sensors, highlighting easy setup and voice assistant support.",
                Audience.TECH_ENTHUSIASTS, AdType.CAROUSEL, "900", "20", -30, 30,
                "smart home, gadgets, home automation, wifi, voice assistant, ai", CampaignStatus.ACTIVE, -1, true, "1.10");
        campaign(demo, "Holiday Gift Guide",
                "A curated gift guide for parents featuring bundles under $50 and free gift wrapping during December.",
                Audience.FAMILIES, AdType.IMAGE, "800", "25", 12, 60, "gifts, holiday, family, kids",
                CampaignStatus.PENDING, 0, false, "1.00");
        Campaign flash = campaign(demo, "Weekend Flash Sale",
                "48-hour sale on office accessories and desk organisers for remote professionals.",
                Audience.PROFESSIONALS, AdType.TEXT, "450", "30", -80, -62, "productivity, remote work, desk setup",
                CampaignStatus.COMPLETED, -62, false, "1.00");
        Campaign travel = campaign(demo, "Summer Travel Escapes",
                "Short video spots showcasing weekend getaway packages with flexible cancellation.",
                Audience.MILLENNIALS, AdType.VIDEO, "600", "15", -50, 10, "travel, getaway, deals, weekend",
                CampaignStatus.PAUSED, -8, false, "1.00");
        Campaign student = campaign(demo, "Student Tech Bundle",
                "Laptop and headphone bundle for students returning to campus this term.",
                Audience.GEN_Z, AdType.TEXT, "300", "10", 3, 33, "student deals, laptop",
                CampaignStatus.REJECTED, 0, false, "1.00");
        student.setRejectionReason("Add clear pricing details and the offer end date to the description.");
        student.setReviewedBy(admin);
        student.setReviewedAt(now.minusDays(2));
        campaignRepository.update(student);

        // ---- other advertisers
        campaign(priya, "FreshCart Weekly Veg Boxes",
                "Seasonal organic vegetable boxes delivered weekly, with the first box half price.",
                Audience.FAMILIES, AdType.IMAGE, "1500", "35", -35, 40,
                "family, organic, home essentials, value pack, healthy eating", CampaignStatus.ACTIVE, -1, false, "1.05");
        Campaign detox = campaign(priya, "Miracle Detox Tea - Guaranteed Results",
                "Lose weight fast with our miracle detox blend. Guaranteed results in 7 days or your money back.",
                Audience.SENIORS, AdType.IMAGE, "400", "15", 2, 32, "detox, health, tea",
                CampaignStatus.PENDING, 0, false, "1.00");
        detox.setFlagged(true);
        detox.setFlagReason("Contains blocked phrase \"guaranteed\"");
        campaignRepository.update(detox);

        campaign(daniel, "VoltGear X2 Smartwatch Launch",
                "Launch campaign for the X2 smartwatch: 10-day battery, AMOLED display and pre-order bonus strap.",
                Audience.TECH_ENTHUSIASTS, AdType.CAROUSEL, "2500", "60", -25, 35,
                "gadgets, smartwatch, wearables, innovation, early access, fitness tracker", CampaignStatus.ACTIVE, -1, true, "1.15");
        campaign(daniel, "Back-to-Work Productivity Pack",
                "Noise-cancelling earbuds and a wireless charger bundle for hybrid workers.",
                Audience.PROFESSIONALS, AdType.TEXT, "700", "20", 5, 40, "productivity, remote work, business tools",
                CampaignStatus.SCHEDULED, 0, false, "1.00");
        campaign(sofia, "Cozy Home Makeover",
                "Spring cushion and throw collection with bundle pricing for living room refreshes.",
                Audience.FAMILIES, AdType.IMAGE, "600", "20", -75, -45, "home decor, cushions, family, value pack",
                CampaignStatus.COMPLETED, -45, false, "1.00");

        // ---- optimization history
        optimizationLogRepository.insert(OptimizationLog.builder().campaignId(smartHome.getId()).userId(demo)
                .type(OptimizationType.SCHEDULE).description("Enabled peak-hour scheduling (18:00–22:00)")
                .appliedAt(now.minusDays(20)).build());
        optimizationLogRepository.insert(OptimizationLog.builder().campaignId(smartHome.getId()).userId(demo)
                .type(OptimizationType.KEYWORDS).description("Added keywords: ai, voice assistant")
                .appliedAt(now.minusDays(18)).build());

        // ---- support tickets
        ticket(demo, "CTR dropped on Autumn Collection", "Click-through rate on my Autumn Collection Launch campaign "
                + "has been lower than I expected this week. Is there anything I should change?", TicketPriority.MEDIUM, 1, null);
        ticket(demo, "How are budget alerts calculated?", "I received an 80% budget alert. Does that include today's "
                + "spend or only completed days?", TicketPriority.LOW, 9,
                "Budget alerts use the total spent so far, including today. You get one alert per campaign when it passes 80%.");
        ticket(daniel, "Payment not showing in balance", "I added $1,500 by card but I want to confirm it is available "
                + "for my scheduled productivity campaign.", TicketPriority.HIGH, 0, null);
        ticket(sofia, "Close my account", "Please deactivate my advertiser account after my campaign finishes.",
                TicketPriority.LOW, 40, "Your campaign has finished and the account has been deactivated as requested.");

        // ---- notifications for the demo advertiser (oldest first)
        notification(demo, NotificationType.INFO, "Welcome to AdOptimize Pro",
                "Add funds in Payments, then create your first campaign.", 89, true);
        notification(demo, NotificationType.SUCCESS, "Campaign completed",
                "\"" + flash.getTitle() + "\" reached its end date.", 61, true);
        notification(demo, NotificationType.SUCCESS, "Campaign approved 🎉",
                "\"" + autumn.getTitle() + "\" was approved and is now live.", 40, true);
        if (travel.isBudgetAlertSent()) {
            notification(demo, NotificationType.WARNING, "80% of budget used",
                    "\"" + travel.getTitle() + "\" has used over 80% of its budget.", 9, false);
        }
        notification(demo, NotificationType.ERROR, "Campaign rejected",
                "\"" + student.getTitle() + "\" was rejected: " + student.getRejectionReason() + " Edit the campaign to resubmit it.", 2, false);
        notification(demo, NotificationType.PENDING, "Campaign submitted",
                "\"Holiday Gift Guide\" has been submitted for admin review.", 1, false);

        log.info("Demo data ready. Advertiser: demo@adpro.com / demo123 - Admin: admin@adpro.com / admin123 (group code from app.admin.group-code)");
    }

    // ------------------------------------------------------------------ builders

    private long user(String name, String email, String password, String company, Role role, boolean active, int daysAgo) {
        User user = User.builder()
                .name(name)
                .email(email)
                .passwordHash(passwordEncoder.encode(password))
                .company(company)
                .role(role)
                .active(active)
                .createdAt(now.minusDays(daysAgo))
                .build();
        long id = userRepository.insert(user);
        if (active) {
            userRepository.updateLastLogin(id, now.minusHours(random.nextInt(72) + 1));
        }
        return id;
    }

    private void payment(long userId, String amount, String brand, String last4, int daysAgo) {
        paymentRepository.insert(Payment.builder()
                .userId(userId)
                .amount(new BigDecimal(amount))
                .cardBrand(brand)
                .cardLast4(last4)
                .description("Account top-up")
                .status(Payment.STATUS_COMPLETED)
                .createdAt(now.minusDays(daysAgo).minusMinutes(random.nextInt(600)))
                .build());
    }

    /**
     * Creates a campaign and its statistics.
     *
     * @param historyEndOffset last day (relative to today) that received traffic; ignored for statuses without delivery
     */
    private Campaign campaign(long userId, String title, String description, Audience audience, AdType adType,
                              String budget, String daily, int startOffset, int endOffset, String keywords,
                              CampaignStatus status, int historyEndOffset, boolean peakHours, String quality) {
        LocalDate start = today.plusDays(startOffset);
        LocalDate end = today.plusDays(endOffset);
        Campaign c = Campaign.builder()
                .userId(userId)
                .title(title)
                .description(description)
                .audience(audience)
                .adType(adType)
                .budget(new BigDecimal(budget))
                .dailyBudget(new BigDecimal(daily))
                .spent(BigDecimal.ZERO)
                .startDate(start)
                .endDate(end)
                .keywords(new ArrayList<>(KeywordListValidator.parse(keywords)))
                .status(status)
                .peakHoursOnly(peakHours)
                .qualityScore(new BigDecimal(quality))
                .createdAt(now.minusDays(Math.max(1, -startOffset + 2)))
                .updatedAt(now.minusDays(1))
                .build();
        if (status != CampaignStatus.PENDING) {
            c.setReviewedAt(c.getCreatedAt().plusHours(6));
        }

        List<DailyStat> stats = new ArrayList<>();
        boolean delivers = status == CampaignStatus.ACTIVE || status == CampaignStatus.PAUSED || status == CampaignStatus.COMPLETED;
        if (delivers) {
            LocalDate lastDay = today.plusDays(historyEndOffset);
            for (LocalDate day = start; !day.isAfter(lastDay) && !day.isAfter(end); day = day.plusDays(1)) {
                BigDecimal remaining = c.getBudget().subtract(c.getSpent());
                if (remaining.compareTo(new BigDecimal("0.50")) < 0) {
                    break;
                }
                BigDecimal target = c.getDailyBudget()
                        .multiply(BigDecimal.valueOf(0.62 + random.nextDouble() * 0.30))
                        .setScale(2, RoundingMode.HALF_UP);
                TrafficModel.Delivery d = TrafficModel.simulate(c, settings, target, c.getDailyBudget().min(remaining), random);
                if (d.isEmpty()) {
                    continue;
                }
                stats.add(DailyStat.builder().statDate(day).impressions(d.impressions()).clicks(d.clicks())
                        .conversions(d.conversions()).spend(d.spend()).build());
                c.setImpressions(c.getImpressions() + d.impressions());
                c.setClicks(c.getClicks() + d.clicks());
                c.setConversions(c.getConversions() + d.conversions());
                c.setSpent(c.getSpent().add(d.spend()));
            }
        }
        c.setBudgetAlertSent(c.getSpent().compareTo(c.getBudget().multiply(new BigDecimal("0.80"))) >= 0);

        c.setId(campaignRepository.insert(c));
        stats.forEach(stat -> stat.setCampaignId(c.getId()));
        if (!stats.isEmpty()) {
            dailyStatRepository.insertAll(stats);
        }
        return c;
    }

    private void ticket(long userId, String subject, String message, TicketPriority priority, int daysAgo, String reply) {
        LocalDateTime created = now.minusDays(daysAgo).minusHours(random.nextInt(8) + 1);
        ticketRepository.insert(SupportTicket.builder()
                .userId(userId)
                .subject(subject)
                .message(message)
                .priority(priority)
                .status(reply == null ? TicketStatus.OPEN : TicketStatus.RESOLVED)
                .adminReply(reply)
                .resolvedAt(reply == null ? null : created.plusHours(5))
                .createdAt(created)
                .build());
    }

    private void notification(long userId, NotificationType type, String title, String message, int daysAgo, boolean read) {
        notificationRepository.insert(Notification.builder()
                .userId(userId)
                .type(type)
                .title(title)
                .message(message)
                .read(read)
                .createdAt(now.minusDays(daysAgo))
                .build());
    }
}
